// <reference types="cypress" />

//import { EventBrief } from '../../page-objects/eventBriefs';
//import { watchFile } from 'fs';
//import { Login } from '../page-objects/login';

describe('Exploring the Event Briefs', () => {
    //const eventBrief = new EventBrief();
    before(function () {
        cy.visit('http://localhost:4200/')
        //cy.visit('https://w3-origin-eal-009057.nonprod.intranet.ibm.com/marketing/events/ews/welcome')
      })


    // it('Validate successful Login', function () {
    //     cy.get('.column > .large').click()
    //     cy.get('#credsDiv').click()
    //     cy.wait(2500)
    //     login.getEmail().type(this.testdata.username)
    //     login.getPassword().type(this.testdata.password, { log: false})
    //     cy.get('#login-button').click()
    //     cy.wait(5000)
    // })

    it('Navigate to Event Brief tab', () => {
        cy.wait(2000)
        cy.get('[ng-reflect-router-link="briefs"] > .bx--side-nav__item > .bx--side-nav__link > .bx--side-nav__link-text').click()
        cy.wait(2000)
        //eventBrief.navigateToTab()
    })

    it('Switch Display', () => {
        cy.get('.bx--toggle__switch').click()
        cy.wait(2000)
        cy.get('.bx--toggle__switch').click()
        //eventBrief.toggleDisplay()
    })

    it('Create an Event Brief', function () {
      cy.get('.bx--toolbar-content > .bx--btn').click()
      cy.wait(1500)
      //namebox for test
      cy.get('#ibm-label-0').click()
      cy.wait(1500)
      cy.get('#ibm-label-0').type('daquantestHybridExp')
      cy.wait(1500)
      //createe brief button
      cy.get('.update--button').click()
      cy.wait(1500)
        // eventBrief.createBrief()
    })

    it('Fill In General Page', function () {
      cy.get('#label-radio-3')
      cy.wait(2000)
      cy.get('#label-radio-0 > .bx--radio-button__appearance').click()
      cy.wait(2000)
      cy.get('#search-1').type('000099AJ')
      cy.wait(2000)
      cy.get('.bx--modal-content > :nth-child(1) > :nth-child(1) > .bx--row > .bx--col-lg-4 > .bx--btn').click()
      cy.wait(2000)
      cy.get('#label-radio-3').click()
      cy.wait(2000)
      cy.get('#label-radio-4').click()
      cy.wait(2000)
      cy.get('#dropdown-1').click()
      cy.get('[title="Lead Generating/Conversion"]').click()
      cy.wait(2000)
      cy.get('[style="margin-bottom: -0.5rem;"] > .bx--col-lg-4 > .bx--btn').click()
      cy.wait(2000)
      cy.get('#label-radio-3').click()
      cy.wait(2000)
        //eventBrief.generalTab()
    })

    it('navigate to Team Tab', function(){ 
      cy.wait(1500)
      cy.get(':nth-child(2) > .bx--tabs__nav-link').click()
      cy.wait(1500)
      cy.get(':nth-child(4) > .bx--col-sm-16 > .bx--btn').click()
      cy.wait(1500)
      cy.get('#search-2').click()
      cy.wait(1500)
      cy.get('#search-2').type('burkek')
      cy.wait(1500)
      cy.get(':nth-child(1) > .bx--col-lg-6 > .bx--btn').click()
      cy.wait(1500)
      cy.get('#label-radio-7 > .bx--radio-button__appearance').click()
      cy.wait(1500)
      cy.get('#label-radio-9 > .bx--radio-button__appearance').click()
      cy.wait(1500)
      cy.get('[style="margin-bottom: -0.5rem;"] > .bx--col-lg-4 > .bx--btn').click()
      cy.wait(2000)
      cy.get(':nth-child(1) > :nth-child(2) > .bx--col-lg-16 > .bx--btn').click()
      cy.get('#search-3').click()
      cy.get('#search-3').type('mandela')
      cy.wait(5000)
      cy.get(':nth-child(1) > .bx--col-lg-12 > .bx--tile').click()
      cy.wait(2000)
      cy.get('#search-3').click()
      cy.wait(2000)
      cy.get('#search-3').clear()
      cy.wait(2000)
      cy.get('#search-3').type('doretha')
      cy.wait(2000)
      cy.get(':nth-child(1) > ul > :nth-child(1) > .bx--col-lg-12 > .bx--tile').click()
      cy.wait(2000)
      cy.get('#search-3').click()
      cy.wait(2000)
      cy.get('#search-3').clear()
      cy.wait(2000)
      cy.get('#search-3').type('phillip martin')
      cy.wait(2000)
      cy.get(':nth-child(1) > ul > :nth-child(1) > .bx--col-lg-12 > .bx--tile').click()
      cy.wait(2000)
      cy.get('.bx--modal-footer > .bx--btn--primary').click()
      cy.wait(2000)
      cy.get('[style="margin-bottom: -0.5rem;"] > .bx--col-lg-4 > .bx--btn').click()
      cy.wait(2000)
        //eventBrief.teamTab()
    })

    it('navigate to financial tab', function() {
      cy.wait(2000)
      cy.get(':nth-child(3) > .bx--tabs__nav-link').click()
      cy.wait(2000)
      cy.get('#label-radio-12 > .bx--radio-button__appearance').click()
      cy.wait(2000)
      cy.get('#number-0').click()
      cy.get('#number-0').type('600')
      cy.wait(2000)
      cy.get('#label-radio-14 > .bx--radio-button__appearance').click()
      cy.wait(2000)
      cy.get('.update--button').click()
        //eventBrief.financialTab()
    })

    it('navigate to metrics tab', function() {
      cy.wait(2000)
      cy.get(':nth-child(4) > .bx--tabs__nav-link').click()
      cy.wait(2000)
      cy.get('#number-1').click()
      cy.wait(2000)
      cy.get('#number-1').type('23')
      cy.wait(2000)
      cy.get('#number-2').click()
      cy.wait(2000)
      cy.get('#number-2').type('24')
      cy.wait(2000)
      cy.get('#number-3').click()
      cy.wait(2000)
      cy.get('#number-3').type('8')
      cy.wait(2000)
      cy.get('#number-4').click()
      cy.wait(2000)
      cy.get('#number-4').type('24')
      cy.wait(2000)
      cy.get('#number-5').click()
      cy.wait(2000)
      cy.get('#number-5').type('8')
      cy.wait(2000)
      cy.get('#number-6').click()
      cy.wait(2000)
      cy.get('#number-6').type('106')
      cy.wait(2000)
      cy.get('#number-7').click()
      cy.wait(2000)
      cy.get('#number-7').type('24')
      cy.wait(2000)
      cy.get('#number-8').click()
      cy.wait(2000)
      cy.get('#number-8').type('8')
      cy.wait(2000)
      cy.get('.bx--col-lg-4 > .bx--btn').click()
        //eventBrief.metricsTab()
    })
    

    it('navigate to experience tab', function() {
      cy.wait(2000)
      cy.get(':nth-child(5) > .bx--tabs__nav-link').click()
      cy.wait(2000)
      cy.get('#label-radio-18 > .bx--radio-button__appearance').click()
      cy.wait(2000)
      cy.get('.bx--btn--primary').click()
      cy.wait(2000)
      cy.get('#label-radio-19 > .bx--radio-button__appearance').click()
      cy.wait(2000)
      cy.get('.bx--btn--primary').click()
      cy.wait(2000)
      cy.get('#label-radio-21 > .bx--radio-button__appearance').click()
      cy.wait(2000)
      // cy.get('#label-radio-25 > .bx--radio-button__appearance').click()
      // cy.wait(2000)
      // cy.get('#label-radio-27 > .bx--radio-button__appearance').click()
      // cy.wait(2000)
      cy.get('.bx--btn--primary').click()
        //eventBrief.experienceHybridTab()
    })

    it('navigate to physical  experience tab', function() {
      cy.wait(4000)
        cy.get('a[title="Experiences"]').click()
        cy.wait(2000)
        cy.get(':nth-child(1) > ibm-clickable-tile > .bx--tile > .bx--tile__content').click()
        cy.wait(2000)
        cy.get('.bx--btn--primary').click()
        cy.wait(2000)
        cy.get('#label-radio-19').click()
        cy.wait(2000)
        cy.get('.bx--btn--primary').click()
        cy.wait(2000)
        cy.get('#label-radio-23 > .bx--radio-button__appearance').click()
        cy.wait(2000)
        cy.get('#label-radio-25 > .bx--radio-button__appearance').click()
        cy.wait(2000)
        cy.get('.bx--btn--primary').click()
        cy.wait(2000)
        cy.get('.bx--tile__content').click()
        cy.wait(2000)
        cy.get('#eventRange-datepicker-input').click()
        cy.wait(2000)
        cy.get('[aria-label="May 19, 2021"]').click()
        cy.wait(2000)
        cy.get('[aria-label="May 25, 2021"]').click()
        cy.wait(2000)
        cy.get('.bx--col-lg-4 > .bx--btn').click()
        cy.wait(2000)
        cy.get('.bx--col-lg-4 > .bx--btn')
        cy.wait(2000)
        cy.get('.bx--no-gutter > .bx--col > .bx--theme-dark > .bx--tabs > .bx--tabs__nav > :nth-child(2) > .bx--tabs__nav-link').click()
        cy.wait(2000)
        // cy.xpath("//body/app-root[1]/main[1]/app-brief-detail[1]/div[1]/div[1]/div[1]/div[1]/div[1]/app-experience-detail[1]/div[1]/div[3]/div[1]/div[1]/app-experience-audience[1]/app-experience-audience-form[1]/div[1]/div[2]/div[1]/ibm-label[1]/label[1]/ibm-dropdown[1]/div[1]/button[1]/*[1]").click({force: true})
        // cy.xpath("//body/app-root[1]/main[1]/app-brief-detail[1]/div[1]/div[1]/div[1]/div[1]/div[1]/app-experience-detail[1]/div[1]/div[3]/div[1]/div[1]/app-experience-audience[1]/app-experience-audience-form[1]/div[1]/div[2]/div[1]/ibm-label[1]/label[1]/ibm-dropdown[1]/div[1]/div[1]/ibm-dropdown-list[1]/ul[1]/li[231]/div[1]").click()
        cy.get('.bx--col-lg-4 > .bx--btn').click()
        cy.get(':nth-child(2) > .bx--col > .bx--theme-dark > .bx--tabs > .bx--tabs__nav > :nth-child(2) > .bx--tabs__nav-link').click()
        cy.get(':nth-child(3) > .update--button').click()
        cy.wait(2000)
        cy.get('#search-2').click()
        cy.get('#search-2').type('canada')
        cy.get('.fixed-height-box > :nth-child(1) > ul > li').click()
        cy.get('.bx--modal-footer > .bx--btn--primary').click()
        cy.get('#label-radio-27 > .bx--radio-button__appearance').click()
        // cy.get('#ibm-label-38').click()
        // cy.get('#ibm-label-38').type('Tardigrades')
        // cy.get('#dropdown-4').click()
        // cy.get('[title="Accounting"] > .bx--list-box__menu-item__option').click()
        // cy.get('#dropdown-5').click()
        // cy.get('[title="Banking"] > .bx--list-box__menu-item__option').click()
        cy.get('.bx--col-lg-4 > .update--button').click()
        cy.wait(2000)
        cy.get('.bx--no-gutter > .bx--col > .bx--theme-dark > .bx--tabs > .bx--tabs__nav > :nth-child(3) > .bx--tabs__nav-link').click()
        cy.wait(2000)
        // cy.get('#ibm-label-81').click()
        // cy.get('#ibm-label-81').type('elevator pitch')
        // cy.get('#ibm-label-82').click()
        // cy.get('#ibm-label-82').type('statement')
        cy.get(':nth-child(1) > .second-half > .bx--text-input').click()
        cy.get(':nth-child(1) > .second-half > .bx--text-input').type('statement')
        cy.get(':nth-child(2) > .second-half > .bx--text-input').click()
        cy.get(':nth-child(2) > .second-half > .bx--text-input').type('statement')
        cy.get('#label-radio-29 > .bx--radio-button__appearance').click()
        cy.get('#ibm-label-44').click()
        cy.get('#ibm-label-44').type('doinggood.com', {force: true})
        cy.get('.bx--col-lg-4 > .bx--btn').click()
        cy.wait(2000)
        // eventBrief.physicalExperience()
    })


    it('navigate to review tab', function() {
      cy.wait(2000)
      cy.get(':nth-child(6) > .bx--tabs__nav-link > #tabStatus > svg').click() 
      cy.wait(2000)
      cy.get('[title="Event Brief Status"] > .bx--accordion__heading > .bx--accordion__arrow').click()
      cy.wait(2000)
      cy.get('[title="Brief field change history"] > .bx--accordion__heading > .bx--accordion__arrow').click()
      cy.wait(2000)
      cy.get('[title="Email history"] > .bx--accordion__heading > .bx--accordion__arrow').click()
      cy.wait(2000)
        //eventBrief.reviewTab()
    })

    // it('navigate to experience tab', function() {
    //     eventBrief.experienceHybridTab()
    // })
    // it('navigate to physical  experience tab', function() {
    //   cy.wait(4000)
    //     cy.get('a[title="Experiences"]').click()
    //     cy.wait(2000)
    //     cy.get('#label-radio-17').click()
    //     cy.wait(2000)
    //     cy.get('.bx--btn--primary').click()
    //     cy.wait(2000)
    //     cy.get('#label-radio-19').click()
    //     cy.wait(2000)
    //     cy.get('.bx--btn--primary').click()
    //     cy.wait(2000)
    //     cy.get('#label-radio-23 > .bx--radio-button__appearance').click()
    //     cy.wait(2000)
    //     cy.get('#label-radio-25 > .bx--radio-button__appearance').click()
    //     cy.wait(2000)
    //     cy.get('.bx--btn--primary').click()
    //     cy.wait(2000)
    //     cy.get('.bx--tile__content').click()
    //     cy.wait(2000)
    //     cy.get('#eventRange-datepicker-input').click()
    //     cy.wait(2000)
    //     cy.get('[aria-label="May 19, 2021"]').click()
    //     cy.wait(2000)
    //     cy.get('[aria-label="May 25, 2021"]').click()
    //     cy.wait(2000)
    //     cy.get('.bx--col-lg-4 > .bx--btn').click()
    //     cy.wait(2000)
    //     cy.get('.bx--col-lg-4 > .bx--btn')
    //     cy.wait(2000)
    //     cy.get('.bx--no-gutter > .bx--col > .bx--theme-dark > .bx--tabs > .bx--tabs__nav > :nth-child(2) > .bx--tabs__nav-link').click()
    //     cy.wait(2000)
    //     cy.xpath("//body/app-root[1]/main[1]/app-brief-detail[1]/div[1]/div[1]/div[1]/div[1]/div[1]/app-experience-detail[1]/div[1]/div[3]/div[1]/div[1]/app-experience-audience[1]/app-experience-audience-form[1]/div[1]/div[2]/div[1]/ibm-label[1]/label[1]/ibm-dropdown[1]/div[1]/button[1]/*[1]").click({force: true})
    //     cy.xpath("//body/app-root[1]/main[1]/app-brief-detail[1]/div[1]/div[1]/div[1]/div[1]/div[1]/app-experience-detail[1]/div[1]/div[3]/div[1]/div[1]/app-experience-audience[1]/app-experience-audience-form[1]/div[1]/div[2]/div[1]/ibm-label[1]/label[1]/ibm-dropdown[1]/div[1]/div[1]/ibm-dropdown-list[1]/ul[1]/li[231]/div[1]").click()
    //     cy.get('.bx--col-lg-4 > .bx--btn').click()
    //     cy.get(':nth-child(2) > .bx--col > .bx--theme-dark > .bx--tabs > .bx--tabs__nav > :nth-child(2) > .bx--tabs__nav-link').click()
    //     cy.get(':nth-child(3) > .update--button').click()
    //     cy.wait(2000)
    //     cy.get('#search-2').click()
    //     cy.get('#search-2').type('canada')
    //     cy.get('.fixed-height-box > :nth-child(1) > ul > li').click()
    //     cy.get('.bx--modal-footer > .bx--btn--primary').click()
    //     cy.get('#label-radio-27 > .bx--radio-button__appearance').click()
        // cy.get('#ibm-label-38').click()
        // cy.get('#ibm-label-38').type('Tardigrades')
        // cy.get('#dropdown-4').click()
        // cy.get('[title="Accounting"] > .bx--list-box__menu-item__option').click()
        // cy.get('#dropdown-5').click()
        // cy.get('[title="Banking"] > .bx--list-box__menu-item__option').click()
        // cy.get('.bx--col-lg-4 > .update--button').click()
        // cy.wait(2000)
        // cy.get('.bx--no-gutter > .bx--col > .bx--theme-dark > .bx--tabs > .bx--tabs__nav > :nth-child(3) > .bx--tabs__nav-link').click()
        // cy.wait(2000)
        // cy.get('#ibm-label-81').click()
        // cy.get('#ibm-label-81').type('elevator pitch')
        // cy.get('#ibm-label-82').click()
        // cy.get('#ibm-label-82').type('statement')
        // cy.get(':nth-child(1) > .second-half > .bx--text-input').click()
        // cy.get(':nth-child(1) > .second-half > .bx--text-input').type('statement')
        // cy.get(':nth-child(2) > .second-half > .bx--text-input').click()
        // cy.get(':nth-child(2) > .second-half > .bx--text-input').type('statement')
        // cy.get('#label-radio-29 > .bx--radio-button__appearance').click()
        // cy.get('#ibm-label-44').click()
        // cy.get('#ibm-label-44').type('doinggood.com', {force: true})
        // cy.get('.bx--col-lg-4 > .bx--btn').click()
        // cy.wait(2000)
        // cy.get('#label-radio-35 > .bx--radio-button__appearance').click()
        // cy.get('#ibm-label-119').click()
        // cy.get('#ibm-label-119').type('mydomain')
        // cy.get('.bx--col-lg-4 > .bx--btn').click()
        // cy.get('.bx--no-gutter > .bx--col > .bx--theme-dark > .bx--tabs > .bx--tabs__nav > :nth-child(4) > .bx--tabs__nav-link').click()
        // cy.get('#label-radio-43 > .bx--radio-button__appearance').click()
        // cy.get('.bx--form-item > .bx--btn').click()
        // cy.get('[title="Event Brief Status"] > .bx--accordion__heading > .bx--accordion__arrow').click()
        // cy.get('app-brief-detail-cteba-review > .bx--accordion__item > .bx--accordion__heading > .bx--accordion__title').click()
        // cy.get('[title="Brief field change history"] > .bx--accordion__heading > .bx--accordion__title').click()
        // cy.get('[title="Email history"] > .bx--accordion__heading > .bx--accordion__title').click()
        //eventBrief.physicalExperience()
    // })
})